name: Collect contract signatures and make PR to update them in Stratus repository

on:
  push:
    branches:
      - main
      - stratus-integration
  workflow_dispatch:

jobs:
  collect-signatures:
    runs-on: ubuntu-latest
    name: Collect signatures

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install mise
        uses: jdx/mise-action@v3
        with:
          github_token: ${{ secrets.GHA_PAT }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .tool-versions
          cache: pnpm
          registry-url: "https://npm.pkg.github.com"
          scope: "@cloudwalk"

      - run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHA_PAT }}

      - name: Generate signatures
        run: ./stratus-integration/generate-signatures.bash
        shell: bash

      - name: Save artifact
        uses: actions/upload-artifact@v6
        with:
          name: contract-signatures
          path: signatures
          overwrite: true
